AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-api

  yolo

Globals:
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET, POST, OPTIONS'"
      AllowHeaders: "'Content-Type, Accept'"
      AllowCredentials: "'*'"
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  CounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: counter/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
      Runtime: python3.10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /resume/increment
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable

  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CounterTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  CounterApi:
    Description: API Gateway endpoint URL for Prod stage for Counter function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resume/increment/"
  CounterFunction:
    Description: Counter Lambda Function ARN
    Value: !GetAtt CounterFunction.Arn
  CounterFunctionIamRole:
    Description: Implicit IAM Role created for Counter function
    Value: !GetAtt CounterFunctionRole.Arn
